### ISSUE TITLE
ghost block in gate

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#1]
ghost block in middle of gate is solid breaking it in creative closes the gate and making think it is active till it is dailed again
![2024-02-03_08 28 44](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/70cc8f2c-4f88-4fd6-bdd3-1e638b1bd8a2)
![2024-02-03_08 33 38](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/a39a4a84-5e0f-45f0-bda1-414f9643e9f3)
![2024-02-03_08 33 25](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/f1caa4a9-be52-4fc7-bcf9-7ae18f97d78a)

**Comment by MineDragonCZ** [comment]
fixed
