### ISSUE TITLE
Gates and JSG tile entities invisible with shaders enabled

### ISSUE THREAD

**Issue by onepieceluffyy** [Tau-ri-Dev/Mod-JSG-1.20.x#11]
Using latest Oculus and Embeddium on forge 47.2.20,

Stargates and other JSG tile entities are visible with shaders disabled, but as soon as they are enabled, they become invisible.
Tested with three different shaderpacks.

Running barebones instance with the following mods
-jsg-1.20.1-5.0.0.0-Alpha
-embeddium-0.3.1+mc1.20.1
-oculus-mc1.20.1-1.6.15
-ferritecore-6.0.1-forge
-modernfix-forge-5.13.0+mc1.20.1

**Comment by onepieceluffyy** [comment]
Produces the following when enabling shaders with gate in view
[log.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14154748/log.txt)

**Comment by MineDragonCZ** [comment]
Fixed in dev
