### ISSUE TITLE
Unable to Scroll Through the Stargate Configuration Menu

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.20.x#13]
Hello, I am having trouble scrolling through the Stargate configuration menu. Can you please assist me with this issue?
![image](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/100013611/35c2a927-2509-4dfe-afa8-d8e5ff9e8745)
I would appreciate any assistance you can provide!
Thanks.

**Comment by Fredyman95** [comment]
JEI - bookmarks?

**Comment by matesaman9910** [comment]
> JEI - bookmarks?

I don't use JEI in 1.20.1

**Comment by matesaman9910** [comment]
> > JEI - bookmarks?
> 
> I don't use JEI in 1.20.1

If you meant it like that

**Comment by MineDragonCZ** [comment]
it's known for me.... I forgot something xd
