### ISSUE TITLE
Not sure why but my game crashed.

### ISSUE THREAD

**Issue by squall2044** [Tau-ri-Dev/Mod-JSG-1.20.x#14]
I tried to build a gate and my game froze for a second and then crashed when I placed the final piece. It has completely killed the world.
I only have 3 mods in place AppliedEnergistics2, JEI, and JSG.
[crash-2024-02-04_08.39.03-server.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14157573/crash-2024-02-04_08.39.03-server.txt)

**Comment by MineDragonCZ** [comment]
Duplicate of #8
