### ISSUE TITLE
Stargate gui doesn't show energy fill level of base block

### ISSUE THREAD

**Issue by xg787** [Tau-ri-Dev/Mod-JSG-1.20.x#17]
![2024-02-04_20 02 22](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/59268579/42c443b6-09c7-409a-bce4-25b11248d438)

![2024-02-04_20 02 26](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/59268579/439cd457-4570-4a06-87ca-bd8ecaad517a)

**Comment by MineDragonCZ** [comment]
Fixed
