### ISSUE TITLE
Bug: Gate become invisible upon completion

### ISSUE THREAD

**Issue by weberlepecheur** [Tau-ri-Dev/Mod-JSG-1.20.x#18]
### Mod version:
5.0.0.1 Alpha

### Forge version:
47.2.0

### Modlist:
JustStargateMod

### Crash report:
No crash report, only latest.log
[latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14167907/latest.log)

### How to reproduce:
- Create a new creative flat world
- Construct the milky way gate vertically
- Upon posing the last block the gate become invisible.

### Screenshoot:
![jsg-5 0 0 1a](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/18701493/254790c5-0a8b-4003-b4f8-c3103fd718a6)

**Comment by MineDragonCZ** [comment]
Do you have shaders enabled?

**Comment by MineDragonCZ** [comment]
Ah, I see where is the problem... It's fixed
