### ISSUE TITLE
energy display glitch

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#20]
energy display does not give accurate reading
![2024-02-05_09 47 44](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/77550068-1e11-4fd9-8952-4d1301f519b5)
![2024-02-05_09 51 09](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/ca0e29f5-ea38-4014-a221-f4eb88cfe254)
shield and gate active^
![2024-02-05_09 47 52](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/912a0dc7-254e-4f2b-89e0-63a0938b42c7)
![2024-02-05_09 53 58](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/084c76cf-ce0b-4f90-9f59-c2d9b7525085)
gate only^
![2024-02-05_09 51 56](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/8a33cc92-ce70-429e-ac54-1c85a4f55857)
![2024-02-05_09 51 47](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/3d831489-92f4-471c-8233-f7f9f07c78b4)
![2024-02-05_09 51 43](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/8e2fb8ed-e1c8-4443-9a86-a4c7086ccacd)
shield only^

**Comment by TheRedCreations** [comment]
And what's wrong?
The Gate recharges the small energy amounts very fast. Why should the gate loose energy?
Cause the fast recharge, there is no difference in energy storage.

**Comment by AvionMorna** [comment]
> And what's wrong? The Gate recharges the small energy amounts very fast. Why should the gate loose energy? Cause the fast recharge, there is no difference in energy storage.

first i will addmit that i was confused and thought what i am guessing is time till close was rf\t after doubling back and double checking the gate doesn't show a rf\t power draw it say it isn't drawing any power even when it is 527 rf\t with gate and shield 27 rf\t for just the gate before time limit and 500 rf\t for just the shield

**Comment by MineDragonCZ** [comment]
the bar shows diference between input power and output power basically
