### ISSUE TITLE
waterlog issues

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#21]
if not built in water gate does not waterlog except for base block
![2024-02-05_10 13 31](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/a6d9335c-b83e-4a15-a621-d989d8baedd2)
![2024-02-05_10 12 57](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/3f100d04-bdb7-4b5d-aa36-1f07f4748be6)
![2024-02-05_10 44 22](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/468f5479-0fca-49d2-839f-f9f14866537a)
when waterlogged only the base block can be unlogged
![2024-02-05_10 37 02](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/c3247e4f-1b05-45a1-9727-df9fab392423)
when blocks are broken around a waterlog gate the water does not flow until base block is unlogged than logged again

![2024-02-05_10 35 25](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/6e8cd3be-bde9-4c3b-91b1-95a04bf47351)
![2024-02-05_10 36 53](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/403c5c6f-5c2d-4f32-ab20-f8358eff0ea9)
![2024-02-05_10 37 02](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/257e1eb8-e0ca-41be-b0e4-5ba31cc88408)

**Comment by MineDragonCZ** [comment]
Fixed
