### ISSUE TITLE
custom menu does shows black screen on initial startup

### ISSUE THREAD

**Issue by MR-Spagetty** [Tau-ri-Dev/Mod-JSG-1.20.x#22]
upon starting a modpack with 5.0.0.1 teh menu just showed a black screen with the we are not associated with mojang text until i was able to navigate to the options menu using the tooltip then when i exited the options menu the menu correctly showed

[latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14175053/latest.log)

**Comment by MineDragonCZ** [comment]
There was problem with website API when occurred
