### ISSUE TITLE
weird crash teleporting away form stargate with tp command

### ISSUE THREAD

**Issue by MR-Spagetty** [Tau-ri-Dev/Mod-JSG-1.20.x#23]
i teleported to a desert village whilst next to a stargate and the my game crashed
[crash-2024-02-06_19.12.30-client.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14175405/crash-2024-02-06_19.12.30-client.txt)

**Comment by MineDragonCZ** [comment]
Fixed
