### ISSUE TITLE
vanishing water

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#24]
water behind a sideways gate vanish after connection
![2024-02-05_22 01 17](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/bd46c87c-46b1-4718-904a-87fcb2ea6c71)
![2024-02-05_22 02 06](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/2bb407ab-588a-472a-93aa-483ea2ac4045)
![2024-02-05_22 09 02](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/239d353e-4a08-4c7c-a105-252a87f65ad9)

**Comment by MineDragonCZ** [comment]
can you please check if the bug still appears in newest version?

**Comment by AvionMorna** [comment]
Will check after work

**Comment by MineDragonCZ** [comment]
Fixed now
