### ISSUE TITLE
invisable gate crashed

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#25]
[crash-2024-02-08_18.40.38-client.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14216675/crash-2024-02-08_18.40.38-client.txt)
gates near bedrock become invisable (i believe known issue) they work with admin (normally) when to put mwgate crystal and it crashed

**Comment by MineDragonCZ** [comment]
fixed
