### ISSUE TITLE
Mod causes server to crash 

### ISSUE THREAD

**Issue by YETIMAN2020** [Tau-ri-Dev/Mod-JSG-1.20.x#26]
the mod causes the server to crash the same jar works fine on client just not on dedicated server 
server host: pebble 
mod version: jsg-1.20.1-5.0.0.1-Alpha.jar

https://mcpaste.io/bf8f1f4985d10598

https://pastebin.com/hgWG3aE1

note it could be because i was adding it to a ATM9 pack but again it loads fine on client 

Local Dedicated server only running JSG crash log : https://pastebin.com/DLhFecZU

**Comment by matesaman9910** [comment]
Same issue: https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/issues/323

**Comment by MineDragonCZ** [comment]
Fixed
