### ISSUE TITLE
Server start crash

### ISSUE THREAD

**Issue by xg787** [Tau-ri-Dev/Mod-JSG-1.20.x#27]
server crashes when started with the mod
[logs.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14255545/logs.txt)

**Comment by matesaman9910** [comment]
Same issue: https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/issues/323

**Comment by MineDragonCZ** [comment]
Fixed
