### ISSUE TITLE
Bug: SERVER CRASHES 

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.20.x#29]
I don't know if I am doing this wrong but no it isn't fixed
![image](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/100013611/1e136a98-b576-447b-a20b-c15da49ad1de)

**Comment by MR-Spagetty** [comment]
i assume that the bit on the right links to a line in the log based on the translation can you please actually send the log here rather than just saying there is an error. without the error itself it is impossible to fix it

**Comment by MR-Spagetty** [comment]
and if you are saying that this is still issue #28 the fix has not been released yet
