### ISSUE TITLE
Mod crashes server

### ISSUE THREAD

**Issue by gramedek** [Tau-ri-Dev/Mod-JSG-1.20.x#3]
### Mod version:
- 5.0.0.0-Alpha

### Minecraft version:
- 1.20.1

### Forge version:
- 47.2.20

### Problem:
Hello, I tried running the mod on a dedicated server, and during the initialization, it apparently tries loading the localPlayer class and crashes the server while doing so.

Here's the crash log:
- [crash-2024-02-03_16.22.44-fml.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14152178/crash-2024-02-03_16.22.44-fml.txt)
- [Pastebin version](https://pastebin.com/PGph9zgS)

The error seems clearly explained on lines 56-61.

**Comment by MineDragonCZ** [comment]
Should be fixed
