### ISSUE TITLE
a block on one spot of the gate disables overlays

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#31]
![2024-02-19_18 04 18](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/ac57d064-1f2b-4bd7-b7d4-2f8b844feb4f)
![2024-02-19_18 04 40](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/0ba9ace4-e3d6-4795-906a-b38eaa33620d)
![2024-02-19_18 06 02](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/965033db-8a83-4f05-a77a-0608185f8d70)

**Comment by MineDragonCZ** [comment]
Not a bug, but I edited the system little bit so you need 3 blocks to disable the overlay actually
