### ISSUE TITLE
underwater gates count as burried

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#32]
![2024-02-19_17 33 37](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/b676f93a-9e80-4f48-89ad-867af608d392)
![2024-02-19_17 48 46](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/39196c7b-2ee7-422b-9b59-56ca6faa8c12)
had to clear water from above the gate and in the ring to make a connection

**Comment by MineDragonCZ** [comment]
Fixed
