### ISSUE TITLE
Stargate lighting bug 

### ISSUE THREAD

**Issue by YETIMAN2020** [Tau-ri-Dev/Mod-JSG-1.20.x#34]
hey the stargates tend to be lit like its day time even though its night 
![2024-02-22_17 11 46](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/64026995/e5a90810-2330-4c3e-ae3b-fc561ddcb8cb)

**Comment by MineDragonCZ** [comment]
fixed
