### ISSUE TITLE
Server won't load the mod

### ISSUE THREAD

**Issue by AgorisEnyo** [Tau-ri-Dev/Mod-JSG-1.20.x#39]
Fatal error caused by the Mod is: 

17.04 18:41:20 [Server] main/FATAL [ne.mi.re.GameData/]: Failed to register some entries, see suppressed exceptions for details
17.04 18:41:20 [Server] INFO java.lang.RuntimeException: null
17.04 18:41:20 [Server] INFO at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:315) ~[forge-1.20.1-47.2.23-universal.jar%23754!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.reduce_blockstate_cache_rebuilds.GameDataMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin,pl:mixin:A}
17.04 18:41:20 [Server] INFO at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.2.23-universal.jar%23754!/:?] {re:classloading}
17.04 18:41:20 [Server] INFO at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.2.23.jar%23750!/:?] {}
17.04 18:41:20 [Server] INFO at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.23.jar%23750!/:?] {}

**Comment by MineDragonCZ** [comment]
I don't think it's a mod problem...
