### ISSUE TITLE
shaders can trigger dark world bug with a larger mod count

### ISSUE THREAD

**Issue by xg787** [Tau-ri-Dev/Mod-JSG-1.20.x#41]
shaders can trigger dark world bug with a larger mod count
![2024-06-12_22 36 00](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/59268579/51d53f26-a3b6-49aa-94af-6e7f627202c8)

**Comment by MineDragonCZ** [comment]
Fixed in dev
