### ISSUE TITLE
please close all issues fixed

### ISSUE THREAD

**Issue by bugggges** [Tau-ri-Dev/Mod-JSG-1.20.x#42]
so first is the fact that if you make a stargate (Milkyway is what I found this on) if you make it horizontal and dial the gate from another gate (aka you travel through the other gate to the horizontal one) if you go through and get out of the event horizon then if you drop back into the event horizon then it will play the you've been killed by the shield noise and kills you to
things that I think you know but I listed to tell you:
-iris does not work
-admin tool does not work
-some names have I were to type (this.is.a.sentance)
-capacitors don't have charge

**Comment by bugggges** [comment]
btw admin does work i just had a mod on lmao

**Comment by MineDragonCZ** [comment]
If you go the opposite way through the gate it will kill you, that Is normal. 

Idk what u mean by "Iris does not work". What part is not working? What do u expect?

Also i didnt catch the part with the names... What do you mean by that please?

About capacitors. You can charge them by any power source.

**Comment by bugggges** [comment]
Creative mode it does not kill you

**Comment by bugggges** [comment]
Some of the items names (the naquadah) have weird text

**Comment by bugggges** [comment]
And if that is intentional then it does not work vertically

**Comment by bugggges** [comment]
Sorry if my tone is not coming through and I'm being annoying I'm not
trying to

**Comment by bugggges** [comment]
oh the text was fixed imma close this ha
