### ISSUE TITLE
Black Textures Bug

### ISSUE THREAD

**Issue by kluas005** [Tau-ri-Dev/Mod-JSG-1.20.x#43]
![screen bug](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/80136064/97dfb491-ee1a-46db-8b89-99882ac2949b)

My Modlist: 

Forge Version: 47.3.1

1. ad_astra-forge-1.20.1-1.15.18.jar
2. ait-1.0.4-1.20.1-release.jar
3. amendments-1.20-1.2.8.jar
4. appleskin-forge-mc1.20.1-2.5.1.jar
5. appliedenergistics2-forge-15.2.4.jar
6. balm-forge-1.20.1-7.3.6-all.jar
7. BetterAdvancements-1.20.1-0.3.2.161.jar
8. BetterF3-7.0.2-Forge-1.20.1.jar
9. botarium-forge-1.20.1-2.3.3.jar
10. carryon-forge-1.20.1-2.1.2.7.jar
11. cloth-config-11.1.118-forge.jar
12. Clumps-forge-1.20.1-12.0.0.4.jar
13. CodeChickenLib-1.20.1-4.4.0.512-universal.jar
14. cofh_core-1.20.1-11.0.2.56.jar
15. comforts-forge-6.3.5+1.20.1.jar
16. Connector-1.0.0-beta.44+1.20.1.jar
17. ConnectorExtras-1.11.1+1.20.1.jar
18. constructionwand-1.20.1-2.11.jar
19. Controlling-forge-1.20.1-12.0.2.jar
20. create-1.20.1-0.5.1.f.jar
21. cristellib-1.1.5-forge.jar
22. curios-forge-5.9.1+1.20.1.jar
23. DungeonsArise-1.20.x-2.1.58-release.jar
24. embeddium-0.3.21+mc1.20.1.jar
25. embeddiumplus-1.20.1-v1.2.13.jar
26. EnderStorage-1.20.1-2.11.0.188-universal.jar
27. entityculling-forge-1.6.6-mc1.20.1.jar
28. ExplorersCompass-1.20.1-1.3.3-forge.jar
29. fabric-api-0.92.2+1.11.8+1.20.1.jar
30. FarmersDelight-1.20.1-1.2.4.jar
31. ferritecore-6.0.1-forge.jar
32. FluxNetworks-1.20.1-7.2.1.15.jar
33. GodlyVampirism-1.20.1-1.10.0.jar
34. Guide-API-VP-1.20.1-2.2.6.jar
35. Jade-1.20.1-forge-11.9.3.jar
36. JadeAddons-1.20.1-forge-5.2.2.jar
37. jei-1.20.1-forge-15.3.0.8.jar
38. journeymap-1.20.1-5.10.0-forge.jar
39. jsg-1.20.1-5.0.2.1-Beta.jar
40. lanserverproperties-1.11.1-forge.jar
41. lionfishapi-1.9.jar
42. L_Enders_Cataclysm-1.99.5 -1.20.1.jar
43. Mekanism-1.20.1-10.4.8.43.jar
44. MekanismGenerators-1.20.1-10.4.8.43.jar
45. modernfix-forge-5.18.1+mc1.20.1.jar
46. moonlight-1.20-2.12.2-forge.jar
47. MouseTweaks-forge-mc1.20.1-2.25.1.jar
48. NaturesCompass-1.20.1-1.11.2-forge.jar
49. oculus-mc1.20.1-1.7.0.jar
50. owo-lib-0.11.2+1.20.jar
51. Quark-4.0-458.jar
52. regeneration-42.0.0.jar
53. resourcefulconfig-forge-1.20.1-2.1.2.jar
54. resourcefullib-forge-1.20.1-2.1.25.jar
55. Searchables-forge-1.20.1-1.0.3.jar
56. spark-1.10.53-forge.jar
57. storagedrawers-1.20.1-12.0.3.jar
58. supplementaries-1.20-2.8.17.jar
59. tempad-forge-1.20.1-2.3.3.jar
60. thermal_dynamics-1.20.1-11.0.1.23.jar
61. thermal_expansion-1.20.1-11.0.1.29.jar
62. thermal_foundation-1.20.1-11.0.6.70.jar
63. tombstone-1.20.1-8.6.6.jar
64. Towns-and-Towers-1.12-Fabric+Forge.jar
65. travelersbackpack-forge-1.20.1-9.1.14.jar
66. vampiricageing-1.20.1-1.3.21.jar
67. Vampirism-1.20.1-1.10.8.jar
68. waystones-forge-1.20-14.1.3.jar
69. Werewolves-1.20.1-2.0.2.3.jar
70. YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
71. YungsApi-1.20-Forge-4.0.5.jar
72. YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
73. YungsBetterDungeons-1.20-Forge-4.0.4.jar
74. YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
75. YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
76. YungsBetterStrongholds-1.20-Forge-4.0.3.jar
77. Zeta-1.0-19.jar

I removed most of the mods, removed embeddium++ and the problem still happens, and only in abydos, reloading with F3 + T, the textures come back, but for a short time and then everything goes black again, this doesn't happen in the other dimensions, I gave a I researched and saw about the incompatibility with embeddium, I don't know if it was fixed in a previous version, but if you don't know about the problem in the current version, it still occurs in the latest version of your mod.

and sorry to take your time, the mod is amazing, and combined with a doctor who tardis, I spend most of the fun using both

**Comment by Fredyman95** [comment]
Try to turn off oculus - everything that mess up with render (iris, oculus, embeddium, optifine…)  will cause issues (on 1.20.x is main issue black world) 

its because we use our own custom loaders - we cant use default loaders (minecraft or forge loaders cant load out models). So we alsways try to find way how to fix these issues but we cant be always compatible with all mods that exists. 😕

**Comment by MineDragonCZ** [comment]
Fixed in dev
