### ISSUE TITLE
Shaders make gate disappear

### ISSUE THREAD

**Issue by KaiKingStreams** [Tau-ri-Dev/Mod-JSG-1.20.x#45]
So when I use shaders the gates vanish but the blocks and everything are still there 
![image](https://github.com/user-attachments/assets/6148624a-c1b8-4e4a-b273-341b1cbdd7e6)

**Comment by Fredyman95** [comment]
We know, we've already contacted the Oculus mod developers and other similar mod developers for help with this problem - but they're silent. They help others with minor problems, but I think they are powerless with it too... we are not giving up yet and we are trying to find a solution.

And yes, we provided them with all the necessary information regarding the problem - including the source code.

**Comment by MineDragonCZ** [comment]
Fixed in dev
