### ISSUE TITLE
darkworld bug (nvidium + embedium) and crash on resource pack reload :|

### ISSUE THREAD

**Issue by xg787** [Tau-ri-Dev/Mod-JSG-1.20.x#46]
![2024-07-14_15 50 03](https://github.com/user-attachments/assets/f14fec02-fa20-4891-9582-2c93ae5419d5)

[crash-2024-07-14_15.40.47-client.txt](https://github.com/user-attachments/files/16228609/crash-2024-07-14_15.40.47-client.txt)

**Comment by xg787** [comment]
after a while of looking i found the whats causing the issue it is a odd interaction with nvidium, jsg and embedium (i am loading nvidium in forge using the connector mod)

**Comment by MineDragonCZ** [comment]
Fixed in dev
