### ISSUE TITLE
Missing page progress in GUI

### ISSUE THREAD

**Issue by FuchsTairn** [Tau-ri-Dev/Mod-JSG-1.20.x#47]
When you put the adress paper in the gate, the bar dont have the fill animation

**Comment by MR-Spagetty** [comment]
can you post a video of this

**Comment by raygradzewicz** [comment]
https://github.com/user-attachments/assets/c4131feb-bc70-45fa-aca7-59d922387298

I experienced the same issue and recorded it. The artifacts at the top are from my recording software, they were not present in game. Tested on version 5.0.3.1-Beta on a fresh world.
