### ISSUE TITLE
Multiple Stargates in 1 village

### ISSUE THREAD

**Issue by RosalindMaximoff** [Tau-ri-Dev/Mod-JSG-1.20.x#49]
![2024-07-15_12 28 03](https://github.com/user-attachments/assets/025c6d69-5e03-4970-b3f2-af2998ea1891)
3 gates 
![2024-07-15_18 10 43](https://github.com/user-attachments/assets/32e289a6-0f38-46f9-a44f-9cdee8c84099)
7 gates   is this some kind of issue but anyway 

![2024-07-15_12 27 51](https://github.com/user-attachments/assets/869711c2-cc26-4c71-b7cc-570f2662e920)
![2024-07-15_12 27 57](https://github.com/user-attachments/assets/37313d51-5e78-40f0-aea6-becffff1734f)
 these last 2 images are when im using Embedium i saw the warning in main menu that my g card is mot matching with emb.. mod i can see symbols circled model

**Comment by MineDragonCZ** [comment]
Visual issue is fixed
