### ISSUE TITLE
Cascading world generation (1.12.2)

### ISSUE THREAD

**Issue by Sutika01** [Tau-ri-Dev/Mod-JSG-1.20.x#53]
So I was trying to create a server for my 1.12.2 modpack and the log said that the mod was causing cascading world gen.
I tried it out with only just stargate and it was the culprit.
The stargate version is jsg-1.12.2-4.11.2.6.jar and the forge is 14.23.5.2860, recreating it is just creating a forge server and just going a couple hundred blocks and you get the error.
I also attached the log for help. 
[debug.log](https://github.com/user-attachments/files/16400839/debug.log)

**Comment by MineDragonCZ** [comment]
Please rewrite this issue to 1.12.2 repo: https://issues.justsgmod.eu/
