### ISSUE TITLE
Bug: Titanium can be mined with wood

### ISSUE THREAD

**Issue by FuchsTairn** [Tau-ri-Dev/Mod-JSG-1.20.x#57]
I dont know if thats an issue but it seems wrong to mine Titanium with wood, just close it if its intended
Thx for your work

**Comment by FuchsTairn** [comment]
i assume the mineable indicator in jade and the recipes of the blocks showable in JEI is not your problem right?

**Comment by MineDragonCZ** [comment]
Fixed in dev
