### ISSUE TITLE
GATE NOT SHOWING

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.20.x#59]
Hi, the gate in my world doesn't show up at all, but it is there because when I break the block, the gate is shown. I can also open the gate menu, but I just can't see the gate.

![image](https://github.com/user-attachments/assets/af89ad29-78c3-49f2-8292-0b706afaa02c)

**Comment by MineDragonCZ** [comment]
Fixed in dev
