### ISSUE TITLE
going through a untravelled gate kills you

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#6]
![2024-02-03_09 09 40](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/738ed356-94a4-4ceb-a09a-68c306cbeb03)
![2024-02-03_09 10 13](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/158761567/caa48412-45ed-4bd1-824e-84fdfaafefa8)
so iff you have two side by side gate and dail one then try to walk through the recieving gate you will die 
but if you walk thought the transmitting gate then walk back through the recieving gate you will be fine

**Comment by MineDragonCZ** [comment]
That's how it works... You can NOT walk through the receiving gate
