### ISSUE TITLE
ComputerCraft function "getGateType()" returns nil

### ISSUE THREAD

**Issue by RGL872** [Tau-ri-Dev/Mod-JSG-1.20.x#60]
![image_2024-08-10_142944617](https://github.com/user-attachments/assets/8b6e8f60-356b-4d84-8067-d8f7e213a81f)
I have triple checked everything was connected to the gate properly when using the function, yet instead of returning either "MILKYWAY", "PEGASUS", or "UNIVERSE", the function simple returns nil

**Comment by MineDragonCZ** [comment]
Fixed in dev
