### ISSUE TITLE
The server crashes after I build a block next to the Stargate redstone output device.

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.20.x#64]
sorry, I would like to provide more information, but the server crashes and doesn't work anymore after this :(
I will restore the backup.

**Comment by matesaman9910** [comment]
UPDATE: Well, I didn't have a moment to spot it before, but it looks like the issue occurs when you break the gate with the device connected to it.

**Comment by matesaman9910** [comment]
Okay, so now I have a server that I really like. But the mod makes the server crash, and when I remove it, it still crashes. Even when I try an older version, it still fails. What should I do now? 😔

**Comment by MineDragonCZ** [comment]
> What should I do now? 😔
Maybe post here some logs? Otherwise idk how can i magically solve the issue :)

**Comment by matesaman9910** [comment]
Sorry, here: https://mclo.gs/7XLAQ0r

**Comment by MineDragonCZ** [comment]
Fixed in dev, thanks for the log
