### ISSUE TITLE
built face down over bedrock

### ISSUE THREAD

**Issue by AvionMorna** [Tau-ri-Dev/Mod-JSG-1.20.x#7]
[crash-2024-02-03_09.15.52-server.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14152283/crash-2024-02-03_09.15.52-server.txt)
Building the gate face down in Y2(3) cause a crash this crash occurs again on reload

**Comment by MineDragonCZ** [comment]
Should be fixed
