### ISSUE TITLE
1.20.1 Box empty ?

### ISSUE THREAD

**Issue by Krimatoria** [Tau-ri-Dev/Mod-JSG-1.20.x#71]
Should there be an empty box near the Gate in the village? Should there be an empty box near the Gate in the village? Or is this a box not from the gate? 
![image](https://github.com/user-attachments/assets/82355de8-4a16-4b7d-aee7-68f563c1eb72)
![image](https://github.com/user-attachments/assets/b1d196d0-8ae3-4175-b01d-5cd0d915644e)

**Comment by MR-Spagetty** [comment]
yes, loot is not yet implemented for any of the structures

**Comment by Fredyman95** [comment]
There are no lootboxes - items we want to add here arent implement yet or we didnt had time to think about loot box for this structure,

**Comment by Krimatoria** [comment]
> There are no lootboxes - items we want to add here arent implement yet or we didnt had time to think about loot box for this structure,

There are no errors in the gate log, just a couple of warnings. And so far everything is fine, I'm studying the mod, it fits into the assembly very interestingly)

[13:11:37] [Worker-ResourceReload-3/WARN] [minecraft/ModelBakery]: Unable to load model: 'jsg:orban_naquadah_generator_block#inventory' referenced from: jsg:orban_naquadah_generator_block#inventory: java.io.FileNotFoundException: jsg:models/item/orban_naquadah_generator_block.json

[13:10:23] [Worker-ResourceReload-3/WARN] [minecraft/ModelBakery]: Exception loading blockstate definition: 'jsg:blockstates/stargate_orlin_base_block.json' missing model for variant: 'jsg:stargate_orlin_base_block#facing=east,facing_vertical=1,orlin_broken=true,render_block=true,waterlogged=true'
--
9259 | [13:10:23] [Worker-ResourceReload-3/WARN] [minecraft/ModelBakery]: Exception loading blockstate definition: 'jsg:blockstates/stargate_orlin_base_block.json' missing model for variant: 'jsg:stargate_orlin_base_block#facing=east,facing_vertical=1,orlin_broken=true,render_block=true,waterlogged=false'
9260 | [13:10:23] [Worker-ResourceReload-3/WARN] [minecraft/ModelBakery]: Exception loading blockstate definition: 'jsg:blockstates/orban_naquadah_generator_block.json' missing model for variant: 'jsg:orban_naquadah_generator_block#'

**Comment by Fredyman95** [comment]
Orlin gate is WIP

**Comment by Krimatoria** [comment]
> Orlin gate is WIP

https://github.com/emilyploszaj/emi/issues/669
And EMI also does not show your creation recipes, if anything can be created at all. The depth of the ores is also not shown yet. I haven't seen anything else yet. I just decided to write right away, since you answered so quickly)

**Comment by Fredyman95** [comment]
> > Orlin gate is WIP
> 
> [emilyploszaj/emi#669](https://github.com/emilyploszaj/emi/issues/669) And EMI also does not show your creation recipes, if anything can be created at all. The depth of the ores is also not shown yet. I haven't seen anything else yet. I just decided to write right away, since you answered so quickly)

Join our discord - you find answers...
