### ISSUE TITLE
Placing an Iris (shield upgrade tier 3) in a tollan gate crashes client [5.0.4.1-Beta]

### ISSUE THREAD

**Issue by Tambzy** [Tau-ri-Dev/Mod-JSG-1.20.x#74]
I just placed an iris (shield upgrade tier 3) in a tollan gate. 
It instantly crashed my client. 

A friend teleported me away before i spawned but if i go to that area, my game crashes again.

**Comment by MineDragonCZ** [comment]
Fixed in dev but thanks for the report
