### ISSUE TITLE
Bug: Crash upon completing the gate construction

### ISSUE THREAD

**Issue by weberlepecheur** [Tau-ri-Dev/Mod-JSG-1.20.x#8]
### Mod version:
5.0.0.0 Alpha

### Forge version:
47.2.0

### Modlist:
JustStargateMod

### Crash report:
[Pastebin](https://pastebin.com/raw/ctfZhf8X)
[crash-2024-02-03_18.59.44-server.txt](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14152486/crash-2024-02-03_18.59.44-server.txt)

[latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14152500/latest.log)

### How to reproduce:
- Create a new creative flat world
- Construct the milky way gate vertically
- Upon posing the last block the crash occurs.

**Comment by MineDragonCZ** [comment]
Should be fixed
